name: Docker-Neovim Integration Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y neovim docker.io
          sudo usermod -aG docker $USER
          docker --version
          nvim --version

      - name: Test Docker Module
        run: |
          mkdir -p ~/.config/nvim/lua
          cp -r lua/docker ~/.config/nvim/lua/
          nvim --headless \
            -c "lua require('docker').setup()" \
            -c "lua if pcall(require, 'docker') then print('✅ Module loaded successfully') else print('❌ Module failed to load') end" \
            -c "qall"
