name: Docker-Neovim Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y neovim docker.io
          sudo usermod -aG docker $USER
          echo "Versions:"
          nvim --version
          docker --version

      - name: Prepare test
        run: |
          mkdir -p ~/.config/nvim/lua
          cp -r lua/docker ~/.config/nvim/lua/
          echo "Directory structure:"
          tree ~/.config/nvim

      - name: Run tests
        run: |
          nvim --headless \
            -c "lua print('Loading module...')" \
            -c "lua local ok, err = pcall(require, 'docker'); if ok then print('✅ Module loaded!') else print('❌ ERROR: '..err) end" \
            -c "lua if require('docker').show_containers then print('✅ Function exists') else print('❌ Missing function') end" \
            -c "q" || echo "Neovim exited with error"
