name: Docker-Neovim Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Neovim
        run: |
          sudo add-apt-repository ppa:neovim-ppa/unstable -y
          sudo apt-get update
          sudo apt-get install -y neovim
          nvim --version

      - name: Setup Docker
        run: |
          sudo apt-get install -y docker.io
          sudo usermod -aG docker $USER
          newgrp docker
          docker run hello-world

      - name: Prepare Test Environment
        run: |
          mkdir -p ~/.config/nvim/lua
          cp -r lua/docker ~/.config/nvim/lua/
          echo "Arquivos copiados:"
          tree ~/.config/nvim/lua -L 3

      - name: Run Tests
        run: |
          nvim --headless \
            -c "lua print('==> Teste de carregamento')" \
            -c "lua local ok, err = pcall(require, 'docker'); print(ok and '✅ Módulo carregado' or '❌ ERRO: '..err)" \
            -c "lua if ok then print('==> Teste de funções'); require('docker').setup(); print('✅ Setup completo') end" \
            -c "q"
